-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg+oGUjN3sxCkjHbTM
bxMhNO11WlT5ddIq4LC3b62LHhygCgYIKoZIzj0DAQehRANCAASnfxTTjmGstdtL
QqAxSWW6rjLLWEMPEXlp6C6UbfT5zfLoEpHvXnp7QQRzYwnzCuKCmz6XS3mlCR2P
C9oYEJ5Z
-----END PRIVATE KEY-----