name: iOS Build with Xcode 16

on:
  push:
    branches:
      - master

jobs:
  build-ios:
    runs-on: macos-15  # macOS-15 이미지를 사용하여 Xcode 16 지원

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Xcode version (Xcode 16)
      - name: Setup Xcode 16
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'

      # 3. Set up Signing Credentials
      - name: Set up Signing Credentials
        run: |
          security create-keychain -p "temp_password" temp.keychain
          security import ./certificate.p12 -k temp.keychain -P "123456" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "temp_password" temp.keychain
          security list-keychains -s temp.keychain
          security unlock-keychain -p "temp_password" temp.keychain
          security set-keychain-settings -lut 3600 temp.keychain

      # 4. 프로비저닝 프로파일 설정
      - name: Set up Provisioning Profile from Project Folder
        run: |
          mkdir -p ~/Library/Developer/Xcode/UserData/Provisioning\ Profiles
          cp ./AppSealing_Wildcard_Distribution_Profile.mobileprovision ~/Library/Developer/Xcode/UserData/Provisioning\ Profiles/
      
      # 5. Install Fastlane using Homebrew
      - name: Install Fastlane
        run: |
          brew install fastlane

      # 6. Run Fastlane lane for TestFlight upload
      - name: Run Fastlane Lane
        env:
          FASTLANE_USER: "puzznic@inka.co.kr"
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: "fcgx-cbfb-jsez-zbir"
          PROFILE: "AppSealing Wildcard Distribution Profile"
        run: |
          fastlane beta --verbose

