name: iOS Build and Upload to App Store

on:
  push:
    branches:
      - master  # master 브랜치에 푸시될 때 실행

jobs:
  build-and-upload:
    runs-on: macos-15  # macOS 15 이미지에서 실행 (Xcode 16 포함)

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Xcode 버전 설정 (선택 사항)
      - name: Setup Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'

      # 3. 인증서 및 개인 키 복원
      - name: Restore Certificate and Private Key
        run: |
          echo "${{ secrets.CERTIFICATE_P12_BASE64 }}" | base64 --decode > certificate.p12
          echo "${{ secrets.PRIVATE_KEY_P12_BASE64 }}" | base64 --decode > private-key.p12
          security create-keychain -p "temp_password" temp.keychain
          security import certificate.p12 -k temp.keychain -P "${{ secrets.CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
          security import private-key.p12 -k temp.keychain -P "${{ secrets.PRIVATE_KEY_PASSWORD }}" -T /usr/bin/codesign
          security list-keychains -s temp.keychain
          security unlock-keychain -p "temp_password" temp.keychain

      # 4. 프로비저닝 프로파일 설정
      - name: Set up Provisioning Profile from Project Folder
        run: |
          mkdir -p ~/Library/Developer/Xcode/UserData/Provisioning\ Profiles
          cp ./AppSealing_Wildcard_Distribution_Profile.mobileprovision ~/Library/Developer/Xcode/UserData/Provisioning\ Profiles/

      # 5. Xcode 빌드 및 아카이브
      - name: Build and Archive iOS App
        run: |
          xcodebuild clean archive \
            -project AiSM_Swift_Fastlane_Github.xcodeproj \
            -scheme AiSM_Swift_Fastlane_Github \
            -archivePath ${{ runner.temp }}/AiSM_Swift_Fastlane_Github.xcarchive

      # 6. IPA 파일 생성
      - name: Export IPA file
        run: |
          xcodebuild -exportArchive \
            -archivePath ${{ runner.temp }}/AiSM_Swift_Fastlane_Github.xcarchive \
            -exportPath ${{ runner.temp }}/build \
            -exportOptionsPlist ExportOptions.plist \
            CODE_SIGN_IDENTITY="Apple Distribution: Inka Entworks Inc. (22X77ENQ2H)" \
            PROVISIONING_PROFILE_SPECIFIER="AppSealing Wildcard Distribution Profile"

      # 7. Upload IPA to App Store Connect using altool
      - name: Upload IPA to App Store Connect
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_PASSWORD: ${{ secrets.APPLE_APP_PASSWORD }}
        run: |
          xcrun altool --upload-app \
            --type ios \
            --file ${{ runner.temp }}/build/AiSM_Swift_Fastlane_Github.ipa \
            --username "$APPLE_ID" \
            --password "$APPLE_APP_PASSWORD"
